version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb+srv://yashaswinigolla99:yash9010@cluster0.qwsv54b.mongodb.net/BudgetData?retryWrites=true&w=majority
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont:
